from src.database.dao.BaseDao import BaseDao
from src.database.model.User import Subscription


class SubscriptionDao(BaseDao):
    model = Subscription

    @classmethod
    async def add_subscriptions(self):
        subscriptions = [
            {'name': 'DEPOP.AU', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},
            {'name': 'DEPOP.DE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},
            {'name': 'DEPOP.FR', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},
            {'name': 'DEPOP.IT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},
            {'name': 'DEPOP.UK', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},
            {'name': 'DEPOP.US', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000, 'price_month': 4500},

            {'name': 'GRAILED.US', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'GRAILED.UK', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'GRAILED.EU', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'GRAILED.CA', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'GRAILED.AU/NZ', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'GRAILED.ASIA', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},

            {'name': 'POSHMARK.AU', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'POSHMARK.CA', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'POSHMARK.US', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},

            {'name': 'SCHPOCK.AT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.DE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.ES', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.FI', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.IT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.NL', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.NO', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.SE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.UK', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'SCHPOCK.US', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},

            {'name': 'VINTED.AT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.BE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.COM', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.CZ', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.DE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.ES', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.FR', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.HU', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.IT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.LT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.LU', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.NL', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.PL', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.PT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.SE', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.SK', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'VINTED.UK', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},

            {'name': 'WALLAPOP.ES', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'WALLAPOP.FR', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'WALLAPOP.IT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
            {'name': 'WALLAPOP.PT', 'price_one_day': 250, 'price_three_day': 500, 'price_week': 1000,
             'price_month': 4500},
        ]
        for subscription in subscriptions:
            await self.add_if_not_exists(**subscription)
