version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "admin"
    container_name: db_bot_app
    volumes:
      - postgresdata:/var/lib/postgresql/data
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: bot_app
    command: [ "/bin/bash", "/GetParserBot/docker/app.sh" ]
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

volumes:
  postgresdata: