"""commit

Revision ID: 29f146d139e7
Revises: fcf292110247
Create Date: 2023-07-05 03:52:12.410770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f146d139e7'
down_revision = 'fcf292110247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing', sa.Column('send_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailing', 'send_at')
    # ### end Alembic commands ###
